// Colors
export const Colors = {
    red: "#FC1441",
    blue: "#157FFB",
    green: "#30A64A",
    grey: "#6D757D",
};

export const PageGutter = { xs: 2, sm: 3, md: "5%", lg: "8%", xl: "10%" };

//  test data
export const covidData = {
    totals: {
        totalConfirmedCases: 63,
        totalDeaths: 0,
        totalRecovered: 0,
        totalActiveCases: 63,
        totalDailyConfirmedCases: 57, // Sum of daily cases
        totalDailyDeaths: 0,
    },
    records: [
        {
            date: "2020/03/05",
            confirmed: 1,
            deaths: 0,
            recovered: 0,
            active: 1,
            dailyConfirmed: 0,
            dailyDeaths: 0,
        },
        {
            date: "2020/03/06",
            confirmed: 1,
            deaths: 0,
            recovered: 0,
            active: 1,
            dailyConfirmed: 0,
            dailyDeaths: 0,
        },
        {
            date: "2020/03/07",
            confirmed: 2,
            deaths: 0,
            recovered: 0,
            active: 2,
            dailyConfirmed: 1,
            dailyDeaths: 0,
        },
        {
            date: "2020/03/08",
            confirmed: 3,
            deaths: 0,
            recovered: 0,
            active: 3,
            dailyConfirmed: 1,
            dailyDeaths: 0,
        },
        {
            date: "2020/03/09",
            confirmed: 7,
            deaths: 0,
            recovered: 0,
            active: 7,
            dailyConfirmed: 4,
            dailyDeaths: 0,
        },
        {
            date: "2020/03/10",
            confirmed: 7,
            deaths: 0,
            recovered: 0,
            active: 7,
            dailyConfirmed: 0,
            dailyDeaths: 0,
        },
        {
            date: "2020/03/11",
            confirmed: 13,
            deaths: 0,
            recovered: 0,
            active: 13,
            dailyConfirmed: 6,
            dailyDeaths: 0,
        },
        {
            date: "2020/03/12",
            confirmed: 17,
            deaths: 0,
            recovered: 0,
            active: 17,
            dailyConfirmed: 4,
            dailyDeaths: 0,
        },
        {
            date: "2020/03/13",
            confirmed: 25,
            deaths: 0,
            recovered: 0,
            active: 25,
            dailyConfirmed: 8,
            dailyDeaths: 0,
        },
        {
            date: "2020/03/14",
            confirmed: 39,
            deaths: 0,
            recovered: 0,
            active: 39,
            dailyConfirmed: 14,
            dailyDeaths: 0,
        },
        {
            date: "2020/03/15",
            confirmed: 52,
            deaths: 0,
            recovered: 0,
            active: 52,
            dailyConfirmed: 13,
            dailyDeaths: 0,
        },
        {
            date: "2020/03/16",
            confirmed: 63,
            deaths: 0,
            recovered: 0,
            active: 63,
            dailyConfirmed: 11,
            dailyDeaths: 0,
        },
    ],
};
